import Head from "next/head";
import { env } from "~/env";
import { Button, ButtonGroup, Container, Heading } from '@chakra-ui/react'
import { useRouter } from "next/router";
import axios from "axios";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
          <Heading>
            Mis ventas
          </Heading>
          <ButtonGroup>
            <Button colorScheme='blue' onClick={() => {
              router.push('/login')
            }}>
              Iniciar sesión
            </Button>
            <Button colorScheme='green' onClick={() => {
              // axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, {
              //   withCredentials: true
              // })
              router.push('/clients/new')
            }}>
              Nuevo cliente
            </Button> 
            <Button colorScheme='purple' onClick={() => {
              axios.post(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, {
                operation_data: new Date(),
                total_amount: 25000,
              }, {
                withCredentials: true
              })
            }}>
              Create Sales
            </Button> 
          </ButtonGroup>
      </Container>
    </>
  );
}
