import Head from "next/head";
import { env } from "~/env";
import { Button, ButtonGroup } from '@chakra-ui/react'
import { useRouter } from "next/router";
import axios from "axios";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>
            {env.NEXT_PUBLIC_BACKEND_BASE_URL}
          </h1>
          <ButtonGroup>
          <Button colorScheme='blue' onClick={() => {
            router.push('/login')
          }}>
            Iniciar sesión
          </Button>
          <Button colorScheme='green' onClick={() => {
            axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, {
              withCredentials: true
            })
          }}>
            Get Sales
          </Button> 
          </ButtonGroup>
          
        </div>
      </main>
    </>
  );
}
